apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-source
spec:
  type: git
  params:
    - name: url
      value: https://github.com/imejri/tekton-tutorial-greeter
    - name: revision
      value: master
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: tekton-tutorial-greeter-image
spec:
  type: image
  params:
    - name: url
      # use minikube internal registry
      value: doker.io/imejri/tekton-tutorial-greeter:latest
      # if you are on OpenShift, use OpenShift interal registry
      #value: "image-registry.openshift-image-registry.svc:5000/tektontutorial/greeter"
